spring:
  application:
    name: renthome-security

  config:
    import: optional:file:.env[.properties]

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${HOST_BD}:${PORT_BD}/${NAME_BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}

server:
  port: 9999
  
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 43200000
    refresh-token-expiration: 86400000