spring:
  application:
    name: renthome-core

  config:
    import: optional:file:.env[.properties]

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${HOST_BD}:${PORT_BD}/${NAME_BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}

server:
  port: 8082

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

