name: Deployment Pipeline For Security Microservice

on: 
  push:
    paths: ['microservices/renthome-security/**', '.github/workflows/pipeline-micro-security.yml']
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Download Maven dependencies
        run: | 
          cd microservices/renthome-security
          mvn dependency:go-offline

  verify:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with 'maven'
        run: |
          cd microservices/renthome-security
          mvn -B verify --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: 'microservices/renthome-security/'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
  
  dockerize-and-push:
    needs: [trivy, verify]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservices/renthome-security
          file: ./microservices/renthome-security/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/renthome-security:latest
